### ISSUE TITLE
IMAP client aborts due to expired session

### ISSUE THREAD

**Issue by mourginakis** [aviate-labs/node-monitor#1]
## Issue

An expired IMAP session throws an exception and closes the email reader thread

Per the logs, the session token is set to last exactly 24 hours

## Specifications

```
2022-12-23 17:12:34:INFO:No Change (6 min)
2022-12-23 17:18:34:INFO:Fetched New Data
2022-12-23 17:18:34:INFO:No Change (6 min)
Exception in thread Thread-1 (email_watcher):
Traceback (most recent call last):
  File "/usr/lib/python3.10/imaplib.py", line 1047, in _command_complete
    typ, data = self._get_tagged_response(tag, expect_bye=logout)
  File "/usr/lib/python3.10/imaplib.py", line 1165, in _get_tagged_response
    self._check_bye()
  File "/usr/lib/python3.10/imaplib.py", line 961, in _check_bye
    raise self.abort(bye[-1].decode(self._encoding, 'replace'))
imaplib.IMAP4.abort: Session expired, please login again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/node-monitor/node_monitor/node_monitor_email.py", line 42, in email_watcher
    status, [number_of_messages] = M.select('INBOX')
  File "/usr/lib/python3.10/imaplib.py", line 756, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/usr/lib/python3.10/imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.10/imaplib.py", line 1049, in _command_complete
    raise self.abort('command: %s => %s' % (name, val))
imaplib.IMAP4.abort: command: SELECT => Session expired, please login again.
2022-12-23 17:24:35:INFO:Fetched New Data
2022-12-23 17:24:35:INFO:No Change (6 min)
```

**Comment by mourginakis** [comment]
As of #53 we no longer have this as a feature.
