### ISSUE TITLE
ChangeEvent class cannot handle a `None` object

### ISSUE THREAD

**Issue by mourginakis** [aviate-labs/node-monitor#2]
## Issue
`self.parent_t2` must've been `None`

## Specifications
```bash
2023-01-11 23:54:56:INFO:Fetched New Data
2023-01-11 23:54:56:INFO:No Change (6 min)
2023-01-12 00:00:56:INFO:Fetched New Data
2023-01-12 00:00:56:INFO:!! Change Detected
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/node-monitor/node_monitor/__main__.py", line 5, in <module>
    nodemonitor.runloop()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 66, in runloop
    self.run_once()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 47, in run_once
    "\n\n".join(str(event) for event in events_actionable)
  File "/root/node-monitor/node_monitor/node_monitor.py", line 47, in <genexpr>
    "\n\n".join(str(event) for event in events_actionable)
  File "/root/node-monitor/node_monitor/node_monitor.py", line 265, in __str__
    case "node_removed": return self.__node_removed()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 217, in __node_removed
    f'Node DC ID: {self.parent_t2["dc_id"]}\n'
TypeError: 'NoneType' object is not subscriptable
```

**Comment by mourginakis** [comment]
```
2023-01-19 15:10:00:INFO:Fetched New Data
2023-01-19 15:10:01:INFO:!! Change Detected
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/node-monitor/node_monitor/__main__.py", line 5, in <module>
    nodemonitor.runloop()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 66, in runloop
    self.run_once()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 47, in run_once
    "\n\n".join(str(event) for event in events_actionable)
  File "/root/node-monitor/node_monitor/node_monitor.py", line 47, in <genexpr>
    "\n\n".join(str(event) for event in events_actionable)
  File "/root/node-monitor/node_monitor/node_monitor.py", line 265, in __str__
    case "node_removed": return self.__node_removed()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 217, in __node_removed
    f'Node DC ID: {self.parent_t2["dc_id"]}\n'
TypeError: 'NoneType' object is not subscriptable
root@ubuntu-s-nodemonitor:~/node-monitor# 
```

**Comment by mourginakis** [comment]
```
2023-02-08 16:10:07:INFO:Fetched New Data
2023-02-08 16:10:07:INFO:!! Change Detected
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/node-monitor/node_monitor/__main__.py", line 5, in <module>
    nodemonitor.runloop()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 66, in runloop
    self.run_once()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 47, in run_once
    "\n\n".join(str(event) for event in events_actionable)
  File "/root/node-monitor/node_monitor/node_monitor.py", line 47, in <genexpr>
    "\n\n".join(str(event) for event in events_actionable)
  File "/root/node-monitor/node_monitor/node_monitor.py", line 264, in __str__
    case "node_added": return self.__node_added()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 207, in __node_added
    f'Node DC ID: {self.parent_t2["dc_id"]}\n'
TypeError: 'NoneType' object is not subscriptable
```

**Comment by mourginakis** [comment]
2023-02-15 08:55:13:INFO:No Change (6 min)
2023-02-15 09:01:13:INFO:Fetched New Data
2023-02-15 09:01:13:INFO:!! Change Detected
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/node-monitor/node_monitor/__main__.py", line 5, in <module>
    nodemonitor.runloop()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 66, in runloop
    self.run_once()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 47, in run_once
    "\n\n".join(str(event) for event in events_actionable)
  File "/root/node-monitor/node_monitor/node_monitor.py", line 47, in <genexpr>
    "\n\n".join(str(event) for event in events_actionable)
  File "/root/node-monitor/node_monitor/node_monitor.py", line 265, in __str__
    case "node_removed": return self.__node_removed()
  File "/root/node-monitor/node_monitor/node_monitor.py", line 217, in __node_removed
    f'Node DC ID: {self.parent_t2["dc_id"]}\n'
TypeError: 'NoneType' object is not subscriptable
root@ubuntu-s-nodemonitor:~/node-monitor#
