### ISSUE TITLE
Database Failed Connection

### ISSUE THREAD

**Issue by mourginakis** [aviate-labs/node-monitor#91]
```
Exception in thread Thread-1 (start_node_monitor):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/node_monitor/__main__.py", line 25, in start_node_monitor
    nm.mainloop()
  File "/app/node_monitor/node_monitor.py", line 162, in mainloop
    self.step()
  File "/app/node_monitor/node_monitor.py", line 156, in step
    self.broadcast_alerts()
  File "/app/node_monitor/node_monitor.py", line 97, in broadcast_alerts
    subscribers = self.node_provider_db.get_subscribers_as_dict()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/node_monitor/node_provider_db.py", line 240, in get_subscribers_as_dict
    self._validate_col_names("subscribers", cols)
  File "/app/node_monitor/node_provider_db.py", line 139, in _validate_col_names
    self.connect()
  File "/app/node_monitor/node_provider_db.py", line 106, in connect
    self.conn = psycopg2.connect(
                ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/eventlet/support/psycopg2_patcher.py", line 46, in eventlet_wait_callback
    state = conn.poll()
            ^^^^^^^^^^^
psycopg2.OperationalError: Connection timed out
        Is the server running on that host and accepting TCP/IP connections?
```

**Comment by mourginakis** [comment]
We're using a pooled connection now so this ticket should no longer be an issue.
